services:
  msapi:
    build:
      context: ./msapi
    ports:
      - "8000:80"
    environment:
      - SUM_SERVICE_URL=http://mssum:80/sum
      - SUB_SERVICE_URL=http://mssub:80/sub
      - ENABLE_CACHE=false
      - VERSION=1.0.0
    depends_on:
      - mssum
      - mssub

  mssub:
    build:
      context: ./mssub
    ports:
      - "8001:80"

  mssum:
    build:
      context: ./mssum
    ports:
      - "8002:80"
