services:
  api:
    image: cquinta/mocapp-api:main
    ports:
      - 8000:8000
    restart: always
    environment:
      APP_VERSION: v1
     
  grpc-server-soma:
    image: cquinta/mocapp-soma:main
    ports:
      - 50051:50051
    restart: always  
    
  grpc-server-sub:
    image: cquinta/mocapp-sub:main
    ports:
      - 50052:50052
    restart: always  
   
    
    