# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculator_sub_pb2 as calculator__sub__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculator_sub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculatorsubStub(object):
    """O serviço Calculator define a função RPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sub = channel.unary_unary(
                '/Calculatorsub/Sub',
                request_serializer=calculator__sub__pb2.SubRequest.SerializeToString,
                response_deserializer=calculator__sub__pb2.SubResponse.FromString,
                _registered_method=True)


class CalculatorsubServicer(object):
    """O serviço Calculator define a função RPC.
    """

    def Sub(self, request, context):
        """O método Sub recebe uma SubRequest e retorna uma SubResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorsubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sub': grpc.unary_unary_rpc_method_handler(
                    servicer.Sub,
                    request_deserializer=calculator__sub__pb2.SubRequest.FromString,
                    response_serializer=calculator__sub__pb2.SubResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Calculatorsub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Calculatorsub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculatorsub(object):
    """O serviço Calculator define a função RPC.
    """

    @staticmethod
    def Sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Calculatorsub/Sub',
            calculator__sub__pb2.SubRequest.SerializeToString,
            calculator__sub__pb2.SubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
