# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator_sub.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator_sub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63\x61lculator_sub.proto\".\n\nSubRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x12\x0f\n\x07number2\x18\x02 \x01(\x05\"\x1d\n\x0bSubResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x33\n\rCalculatorsub\x12\"\n\x03Sub\x12\x0b.SubRequest\x1a\x0c.SubResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_sub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBREQUEST']._serialized_start=24
  _globals['_SUBREQUEST']._serialized_end=70
  _globals['_SUBRESPONSE']._serialized_start=72
  _globals['_SUBRESPONSE']._serialized_end=101
  _globals['_CALCULATORSUB']._serialized_start=103
  _globals['_CALCULATORSUB']._serialized_end=154
# @@protoc_insertion_point(module_scope)
