{
 "title": "Mssub",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency(ms/req)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_sum{http_target=\"/sub\"}[1m])/rate(http_server_duration_milliseconds_count{http_target=\"/sub\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mssub CPU Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{container_name=\"microservice-sample-mssub-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mssub Memory Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_percent_ratio{container_name=\"microservice-sample-mssub-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mssub RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count{http_target=\"/sub\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}