[project]
name = "microservice-sub"
version = "0.1.0"
description = "Micosserviço de subtração"
readme = "README.md"

dependencies = [
    "fastapi[standard]",
    "opentelemetry-api",
    "opentelemetry-instrumentation-fastapi",
    "opentelemetry-instrumentation-requests",
    "opentelemetry-exporter-otlp",
    "opentelemetry-exporter-prometheus==0.63b1",
    "opentelemetry-instrumentation-httpx",
    "opentelemetry-sdk",
    "config"
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]
