name: Build and Push Docker Images

on:
  push:
    branches:
      - '*'

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar a imagem da API
        uses: docker/build-push-action@v6
        with:
          context: ./msapi
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mocapp-api:${{ github.sha }}
         

  build-and-push-soma:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar ambiente Python para testes
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Você pode ajustar para a versão que está usando

      - name: Instalar dependências e executar testes
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic httpx pytest
          cd ./mssum
          pytest -v app/test_main.py


      - name: Construir e publicar a imagem do serviço de soma
        uses: docker/build-push-action@v6
        with:
          context: ./mssum
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mocapp-soma:${{ github.sha }}
         

  build-and-push-sub:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Python para testes
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Você pode ajustar para a versão que está usando

      - name: instalar o uv 
        uses: astral-sh/setup-uv@v3
        
      - name: Adicionar dependências de testar 
        run: |
            cd ./mssub
            uv add --dev pytest
            uv run pytest test_main.py
      
      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar a imagem do serviço de subtração
        uses: docker/build-push-action@v6
        with:
          context: ./mssub
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mocapp-sub:${{ github.sha }}
          
