name: Build and Push Docker Images

on:
  push:
    branches:
      - '*'

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar a imagem da API
        uses: docker/build-push-action@v6
        with:
          context: ./msapi
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mocapp-api:${{ github.sha }}
         # cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mocapp-api:buildcache
         # cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mocapp-api:buildcache,mode=max

  build-and-push-soma:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar a imagem do serviço de soma
        uses: docker/build-push-action@v6
        with:
          context: ./mssum
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mocapp-soma:${{ github.sha }}
          #cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mocapp-soma:buildcache
          #cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mocapp-soma:buildcache,mode=max

  build-and-push-sub:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v4

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e publicar a imagem do serviço de subtração
        uses: docker/build-push-action@v6
        with:
          context: ./mssub
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mocapp-sub:${{ github.sha }}
          #cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mocapp-sub:buildcache
          #cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mocapp-sub:buildcache,mode=max
